# Site settings
# in the templates available like {{ site.myvariable }}.
title: Austin’s Blog
email: austin.cq@foxmail.com
brand: Austin huang
headline: 前端探索者
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huangdaxing.top" # the base hostname & protocol for your site
copyright: huangdaxing.top| Copyright © 2016 huangdaxing. All rights reserved. | 保留所有权利。| 

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 977580350@QQ.com

